@echo off
set JAR=target\mi-playlist-0.0.1-SNAPSHOT.jar
echo Building JAR...
call mvn -DskipTests package
echo Killing old process...
for /f "tokens=5" %%a in ('netstat -ano ^| find ":8080"') do taskkill /PID %%a /F
echo Starting new app...
start java -jar %JAR%
echo App running on http://localhost:8080
